# [Info]
site_name: Charles Le's Notebook # 左上角的标题
site_url: https://charleschile.github.io/Notebook #这个是home page的位置，比如https://charleschile.github.io/Notebook，serve的话就会运行在http://127.0.0.1:8000/Notebook/
site_author: 乐驰
site_description: 乐驰的个人笔记

# [Extra]
extra_css:
  - stylesheets/basic.css
  - stylesheets/admonition.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.css

# [UI]
## [top]
theme:
  name: material
  # font:
  #   text: Source Sans Pro
  #   code: Source Code Pro
  features: 
    - navigation.instant
    - navigation.tracking
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github


  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: pink

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue grey
      accent: pink

# edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [top-right corner]
repo_url: https://charleschile.github.io/ # 右上角点击跳转的链接
repo_name: charleschile/Notebook # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2024 乐驰 # 左下角的版权声明
## [bottom-right corner]

extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/charleschile/
      name: GitHub | charleschile

# [Navigation]
nav:
  - Home Page:
    - index.md

  - EECS Course:
    - Course/index.md

    - CMU 15445:
      - Course/15445/1.md
      - Course/15445/15445面试问题.md

    - ETH Zurich Digital Design and Computer Architecture:
      - Course/ddca/ddca.md

    - Stanford CS144:
      - Course/cs144/information.md

    - C++ Fundamental:
      - Course/cppFundamental/语法基础课1.md
      - Course/cppFundamental/语法基础课5.md
      - Course/cppFundamental/语法基础课6.md
      - Course/cppFundamental/语法基础课7.md
      - Course/cppFundamental/语法基础课8.md



    - Duke Introductory C Programming:
      - Course/dukeC/1_information.md
      - Course/dukeC/2.md

    - Harvard CS50's introduction to computer science:
      - Course/cs50/CS50 intoduction to computer science.md

    - Berkeley CS61A Structure and Interpretation of Computer Programs:
      - Course/cs61a/information.md
      - Course/cs61a/week1.md

    - Berkeley CS61B Data Structures and Algorithms:
      - Course/cs61b/information.md
      - Course/cs61b/week1.md
      - Course/cs61b/project0.md
      - Course/cs61b/lab1.md
      - Course/cs61b/week2.md

    - C++ Primer:
      - Course/cppPrimer/cppPrimer.md

    - 北京大学程序设计与算法:
      - Course/peking/程序设计与算法.md
      - Course/peking/计算导论与C语言基础.md
    


  - Programming Problem:
    - Problem/index.md
    - 算法基础课:
      - Problem/acwing/算法基础课基础算法.md
      - Problem/acwing/算法基础课数据结构.md 
      - Problem/acwing/算法基础课搜索与图论.md 
      - Problem/acwing/算法基础课动态规划.md 
      - Problem/acwing/算法基础课贪心.md

    
    - LeetCode:
      - Problem/lc/LeetCode.md
      - Problem/lc/Leetcode hot 100.md
    

    - 代码随想录:
      - Problem/programmercarl/algorithm.md
      - Problem/programmercarl/代码随想录.md

    - 周赛:
      - Problem/contest/contest.md

    - 洛谷题单:
      - 入门1 顺序结构:
        -  Problem/luogu/入门1顺序结构.md

    - 一些技巧:
      - Problem/skill/skills.md

    - 面试相关:
      - Problem/interview/快速面试准备.md
      - Problem/interview/javaguide常考内容.md
      - Problem/interview/笔试练习.md
      - Problem/interview/面试算法准备.md
      - Problem/interview/项目面试问题总结.md

  - Software Development Project:
    - 支付宝前锋营:
      - Project/ant.md
    - 字节跳动青训营后端:
      - Project/bytedance/第五届字节跳动青训营后端专场.md







  - Tool:
    
    - Tool/index.md

    - MkDocs-Material:
      - Tool/mkdocs/MkDocs Material.md
      - Tool/mkdocs/Online personal notebook plan.md
      - Tool/mkdocs/MkDocs美化.md

    - MacBook:
      - Tool/mac/remacbook.md
      - Tool/mac/troubleshooting.md

    - MIT Missing Semester:
      - Tool/MIT/missing_semester.md

    - Systematic review and Meta-analysis:
      - Tool/systematicReview/notes.md
      - Tool/systematicReview/jhu.md
      - Tool/systematicReview/bilibilil.md

    - git:
      - Tool/git/git.md

    - Vim:
      - Tool/vim/vim.md

    - sublime text:
      - Tool/sublime/sublime.md

    - Resume:
      - Tool/resume/resume.md

  - About & Others:
    - About/me.md
    - About/test.md
    - About/interesting.md








markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Content
  - tables
  - pymdownx.snippets:
      auto_append:
        - includes/abbr.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      # linenums: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  
