# [Info]
site_name: Charles Le's Notebook # 左上角的标题
site_url: https://charleschile.github.io/Notebook
site_author: 乐驰
site_description: 乐驰的个人笔记

# [Extra]
extra_css:
  - stylesheets/basic.css
  - stylesheets/admonition.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.css

# [UI]
## [top]
theme:
  name: material
  # font:
  #   text: Source Sans Pro
  #   code: Source Code Pro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github


  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: pink

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue grey
      accent: pink

# edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [top-right corner]
repo_url: https://charleschile.github.io/Notebook # 右上角点击跳转的链接
repo_name: charleschile/Notebook # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2023 乐驰 # 左下角的版权声明
## [bottom-right corner]

extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/charleschile
      name: GitHub | charleschile

# [Navigation]
nav:
  - Home Page:
    - index.md
    - plan.md



  - Computer Science Course:
    - Course/index.md

    - Harvard CS50's introduction to computer science:
      - Course/cs50/CS50 intoduction to computer science.md

    - Berkeley CS61A Structure and Interpretation of Computer Programs:
      - Course/cs61a/information.md
      - Course/cs61a/week1.md

    - Berkeley CS61B Data Structures and Algorithms:
      - Course/cs61b/information.md
      - Course/cs61b/week1.md

    - C++ Primer:
      - Course/cppPrimer/cppPrimer.md

    - 北京大学程序设计与算法:
      - Course/peking/程序设计与算法.md
      - Course/peking/计算导论与C语言基础.md
    
    - Duke Introductory C Programming:
      - Course/dukeC/intro.md
      - Course/dukeC/programmingFundamentals.md

  - Programming Problem:
    - Problem/index.md
    - 语法基础课:
      - Problem/acwing/语法基础课5.md
      - Problem/acwing/语法基础课6.md
      - Problem/acwing/语法基础课7.md
      - Problem/acwing/语法基础课8.md
    - 洛谷题单:
      - 入门1 顺序结构:
        -  Problem/luogu/入门1顺序结构.md

    - 算法基础课:
      - Problem/acwing/算法基础课基础算法.md
    - 字节跳动青训营笔试训练题:
      - Problem/bytedance/backendDay1.md
      - Problem/bytedance/backendDay2.md
      - Problem/bytedance/backendDay3.md
      - Problem/bytedance/backendDay4.md
      - Problem/bytedance/backendDay5.md
      - Problem/bytedance/backendDay6.md
      - Problem/bytedance/backendDay7.md
      - Problem/bytedance/backendDay8.md
    
    - acwing寒假每日一题:
      - Problem/winter/everyday.md


  - Software Development Project:
    - 支付宝前锋营:
      - Project/ant.md
    - 字节跳动青训营:
      - Project/bytedance/第五届字节跳动青训营后端专场.md




  - Reprinted Article:
    - Article/周信静.md
    - Article/OPTO奋斗史.md
    
    - Article/鬲融.md



  - Tool:
    
    - Tool/index.md
    - MkDocs-Material:
      - Tool/mkdocs/MkDocs Material.md
      - Tool/mkdocs/Online personal notebook plan.md
      - Tool/mkdocs/MkDocs美化.md
    - MacBook:
      - Tool/mac/remacbook.md
    - MIT Missing Semester:
      - Tool/MIT/missing_semester.md
    - Systematic review and Meta-analysis:
      - Tool/systematicReview/notes.md
      - Tool/systematicReview/jhu.md
      - Tool/systematicReview/bilibilil.md
  


  - Blog:
    
    - 随笔集:
      - Blog/informalEssay/2301-2302.md
    - 杂想:
      - Blog/关于web 3.0的信息和想法.md
    - 讲稿: 
      - Article/关于学习的意义.md
      - Blog/高考作文.md

  - About & Others:
    - About/me.md
    - About/test.md








markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Content
  - tables
  - pymdownx.snippets:
      auto_append:
        - includes/abbr.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      # linenums: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  